# Generated by Django 2.2.5 on 2022-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=11, unique=True, verbose_name='CPF do cliente')),
                ('name', models.CharField(max_length=300, verbose_name='Nome do cliente')),
            ],
        ),
    ]
