# Generated by Django 2.2.5 on 2022-02-11 21:17

import cpf_field.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=cpf_field.models.CPFField(default=django.utils.timezone.now, max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
