# Generated by Django 2.2.5 on 2022-02-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedeVaregista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome do varegista')),
                ('sold_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de venda')),
                ('total', models.IntegerField(verbose_name='Total de registros')),
            ],
        ),
    ]
