# Generated by Django 2.2.5 on 2022-02-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeVaregista', '0002_auto_20220211_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redevaregista',
            name='sold_at',
            field=models.DateTimeField(verbose_name='Data de venda'),
        ),
    ]
