# Generated by Django 2.2.5 on 2022-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220211_2119'),
        ('redeVaregista', '0003_auto_20220211_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='redevaregista',
            name='customer',
            field=models.ManyToManyField(to='customer.Customer'),
        ),
    ]
